### ISSUE TITLE
Create a config file in /etc for Fpkg

### ISSUE THREAD

**Issue by KitsuneSemCalda** [FpkgProject/Fpkg#6]
Some settings are better in a config file in /etc to improve usability.

Example:
```ini
# 
# /etc/fpkg.conf
#

[options]
ShowForks = "YES"
AllowInstallingForks = "YES"
SizeOfList = 7
```

**Comment by RedsonBr140** [comment]
It might be helpful: https://github.com/IbrahimShahzad/gonfigure
I'm trying tomorrow 😉
