### ISSUE TITLE
Support to build dependencies

### ISSUE THREAD

**Issue by KitsuneSemCalda** [FpkgProject/Fpkg#7]
In some cases, to use `make` it is necessary to have the compiler of the language that may not have been implemented yet, my idea is to use the github api to check if the system has the compiler, if it does not exist, compile the compiler/interpreter before compile the program

**Comment by RedsonBr140** [comment]
Where does Github API comes in? Are you thinking about check all the languages that the project uses and install compilers/interpreters for them?

**Comment by KitsuneSemCalda** [comment]
exactly
